### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by steventlamb** [azavea/django-tinsel#4]
Discovered using otm2-vagrant.
```
[21/Nov/2014 17:12:34] "GET / HTTP/1.0" 200 2443
/usr/local/otm/env/local/lib/python2.7/site-packages/django_tinsel/decorators.py:87: DeprecationWarning: The mimetype keyword argument is deprecated, use content_type instead
  RequestContext(request), **kwargs)
```

**Comment by maurizi** [comment]
@steventlamb I don't think this is a problem with Django-tinsel, since the mimetype keyword is not used on the offending line: https://github.com/azavea/django-tinsel/blob/master/django_tinsel/decorators.py#L86-L87
